# Generated by Django 6.0.5 on 2026-05-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.CharField(choices=[('morning', '08:00–13:00'), ('evening', '13:00–18:00')], default='morning', max_length=20),
        ),
    ]
