# Generated by Django 6.0.5 on 2026-05-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
