# Generated by Django 6.0.5 on 2026-05-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('doctor', 'Врач'), ('registry', 'Регистратор'), ('lab_tech', 'Лаборант / Диагност'), ('admin', 'Администратор')], max_length=20),
        ),
    ]
