# Generated by Django 6.0.5 on 2026-05-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_schedule',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
