# Generated by Django 6.0.5 on 2026-06-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_work_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hospital_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Больницы (из Global DB)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('doctor', 'Врач'), ('registry', 'Регистратор'), ('lab_tech', 'Лаборант / Диагност'), ('admin', 'Администратор'), ('medcore_admin', 'MedCore Admin')], max_length=20),
        ),
    ]
