# Generated by Django 6.0.5 on 2026-05-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempDecryptedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('doctor_id', models.IntegerField()),
                ('patient_pinfl', models.CharField(max_length=14)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('decrypted_data', models.JSONField(verbose_name='Временные дешифрованные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
