# Generated by Django 6.0.5 on 2026-05-18 18:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinfl', models.CharField(max_length=14, unique=True, verbose_name='ПИНФЛ')),
                ('passport', models.CharField(max_length=20, unique=True, verbose_name='Серия и номер паспорта')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО пациента')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('blood_group', models.CharField(blank=True, choices=[('O(I)', 'O(I)'), ('A(II)', 'A(II)'), ('B(III)', 'B(III)'), ('AB(IV)', 'AB(IV)')], max_length=10, null=True, verbose_name='Группа крови')),
                ('rh_factor', models.CharField(blank=True, choices=[('+', 'Rh+'), ('-', 'Rh-')], max_length=1, null=True, verbose_name='Резус-фактор')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рост (см)')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес (кг)')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Аллергии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EncryptedMedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField(verbose_name='ID Врача (Local DB)')),
                ('doctor_name', models.CharField(max_length=255, verbose_name='ФИО Врача')),
                ('disease_name', models.CharField(max_length=255, verbose_name='Название болезни')),
                ('encrypted_payload', models.BinaryField(verbose_name='Зашифрованные медицинские данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient')),
            ],
        ),
    ]
