# Generated by Django 6.0.5 on 2026-05-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='chronic_diseases',
            field=models.TextField(blank=True, null=True, verbose_name='Хронические/Врожденные заболевания'),
        ),
    ]
