# Generated by Django 6.0.5 on 2026-05-21 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_chronic_diseases'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255, verbose_name='Название исследования')),
                ('status', models.CharField(choices=[('pending', 'Не начал'), ('in_progress', 'Ведется работа'), ('completed', 'Работа сделана')], default='pending', max_length=20, verbose_name='Статус')),
                ('lab_tech_id', models.IntegerField(blank=True, null=True, verbose_name='ID Лаборанта/Врача')),
                ('lab_tech_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО Лаборанта')),
                ('report', models.TextField(blank=True, null=True, verbose_name='Отчет/Заключение')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lab_images/', verbose_name='Снимок/Фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='patients.patient', verbose_name='Пациент')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='patients.encryptedmedicalrecord', verbose_name='Связанная запись')),
            ],
        ),
    ]
